local status_ok, nvimtree_config = pcall(require, "nvim-tree")
if not status_ok then
  return
end


nvimtree_config.setup({
  --sort_by = "case_sensitive",
  view = {
    side = "right",
    adaptive_size = true,
    mappings = {
      list = {
        { key = { "<CR>", "o", "<2-LeftMouse>" }, action = "edit" },
        --{ key = "<C-e>",                          action = "edit_in_place" },
        --{ key = "O",                              action = "edit_no_picker" },
        --{ key = { "<C-]>", "<2-RightMouse>" },    action = "cd" },
        { key = { "<C-]>", "<LeftMouse><RightMouse>" },    action = "cd" },
        { key = "<C-v>",                          action = "vsplit" },
        { key = "<C-x>",                          action = "split" },
        { key = "<C-t>",                          action = "tabnew" },
        --{ key = "<",                              action = "prev_sibling" },
        --{ key = ">",                              action = "next_sibling" },
        --{ key = "P",                              action = "parent_node" },
        --{ key = "<BS>",                           action = "close_node" },
        { key = "<Tab>",                          action = "preview" },
        --{ key = "K",                              action = "first_sibling" },
        --{ key = "J",                              action = "last_sibling" },
        { key = "I",                              action = "toggle_git_ignored" },
        { key = ".",                              action = "toggle_dotfiles" },
        --{ key = "U",                              action = "toggle_custom" },
        { key = "R",                              action = "refresh" },
        { key = "a",                              action = "create" },
        { key = "D",                              action = "remove" },
        { key = "d",                              action = "trash" },
        { key = "r",                              action = "rename" },
        { key = "<C-r>",                          action = "full_rename" },
        { key = "x",                              action = "cut" },
        { key = "c",                              action = "copy" },
        { key = "p",                              action = "paste" },
        { key = "y",                              action = "copy_name" },
        { key = "Y",                              action = "copy_path" },
        { key = "gy",                             action = "copy_absolute_path" },
        --{ key = "[e",                             action = "prev_diag_item" },
        --{ key = "[c",                             action = "prev_git_item" },
        --{ key = "]e",                             action = "next_diag_item" },
        --{ key = "]c",                             action = "next_git_item" },
        { key = "-",                              action = "dir_up" },
        { key = "s",                              action = "system_open" },
        { key = "f",                              action = "live_filter" },
        { key = "F",                              action = "clear_live_filter" },
        { key = "q",                              action = "close" },
        { key = "W",                              action = "collapse_all" },
        { key = "E",                              action = "expand_all" },
        --{ key = "S",                              action = "search_node" },
        --{ key = ".",                              action = "run_file_command" },
        { key = "<C-k>",                          action = "toggle_file_info" },
        { key = "g?",                             action = "toggle_help" },
        { key = "m",                              action = "toggle_mark" },
        { key = "bmv",                            action = "bulk_move" },
      }, -- END_DEFAULT_MAPPINGS
    },
  },
  renderer = {
      add_trailing = true,
      group_empty = true,
      highlight_git = true,
      full_name = false,
      root_folder_modifier = ":~",
      indent_markers = {
         enable = true,
         icons = {
            corner = "└",
            edge = "│",
            item = "│",
            none = " ",
         },
      },
      icons = {
         webdev_colors = true,
         git_placement = "after",
         padding = " ",
         symlink_arrow = " ➛ ",
         show = {
            file = true,
            folder = true,
            folder_arrow = true,
            git = true,
         },
         glyphs = {
            default = "",
            symlink = "",
            bookmark = "",
            git = {
              unstaged = "",
              staged = "S",
              unmerged = "",
              renamed = "➜",
              deleted = "",
              untracked = "U",
              ignored = "◌",
            },
            folder = {
              default = "",
              open = "",
              empty = "",
              empty_open = "",
              symlink = "",
            },
         },
      },
      special_files = { "Cargo.toml", "Makefile", "README.md", "readme.md" },
      symlink_destination = true,
  },
  filters = {
    dotfiles = false,
  },
  git = {
    ignore = false,
  },
  diagnostics = {
    enable = true,
    show_on_dirs = false,
    debounce_delay = 50,
    icons = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    },
  },
})


-- different icons

-- default = "",
-- symlink = "",
-- folder = {
--    arrow_closed = "",
--    arrow_open = "",
--    default = "",
--    open = "",
--    empty = "",
--    empty_open = "",
--    symlink = "",
--    symlink_open = "",
-- },
-- git = {
--    unstaged = "✗",
--    staged = "✓",
--    unmerged = "",
--    renamed = "➜",
--    untracked = "★",
--    deleted = "",
--    ignored = "◌",
-- },
